services:
  - type: web
    name: multi-nginx
    runtime: docker
    rootDir: nginx
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore

  - type: web
    name: multi-server
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: multi-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: multi-redis
          property: port
      - key: PGHOST
        fromService:
          type: postgres
          name: multi-postgres
          property: host
      - key: PGPORT
        fromService:
          type: postgres
          name: multi-postgres
          property: port
      - key: PGUSER
        fromService:
          type: postgres
          name: multi-postgres
          property: user
      - key: PGPASSWORD
        fromService:
          type: postgres
          name: multi-postgres
          property: password
      - key: PGDATABASE
        fromService:
          type: postgres
          name: multi-postgres
          property: database

  - type: worker
    name: multi-worker
    runtime: docker
    rootDir: worker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: multi-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: multi-redis
          property: port

  - type: redis
    name: multi-redis
    plan: free
    region: singapore

databases:
  - name: multi-postgres
    databaseName: values
    user: postgres
    plan: free
    region: singapore