services:
  - type: web
    name: multi-server
    runtime: docker
    repo: https://github.com/daisoaihiep/multi-docker
    region: singapore
    plan: free
    rootDir: server
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          name: multi-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: multi-redis
          type: redis
          property: port
      - key: PGHOST
        fromService:
          name: multi-postgres
          type: postgres
          property: host
      - key: PGPORT
        fromService:
          name: multi-postgres
          type: postgres
          property: port
      - key: PGUSER
        fromService:
          name: multi-postgres
          type: postgres
          property: user
      - key: PGPASSWORD
        fromService:
          name: multi-postgres
          type: postgres
          property: password
      - key: PGDATABASE
        fromService:
          name: multi-postgres
          type: postgres
          property: database

  - type: worker
    name: multi-worker
    runtime: docker
    repo: https://github.com/daisoaihiep/multi-docker
    region: singapore
    plan: free
    rootDir: worker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          name: multi-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: multi-redis
          type: redis
          property: port

databases:
  - name: multi-postgres
    databaseName: values
    user: postgres

  - name: multi-redis
    type: redis