services:
  - type: web
    name: multi-nginx
    runtime: docker
    rootDir: nginx
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_HOST
        value: multi-server

  - type: web
    name: multi-server
    runtime: docker
    rootDir: server
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: multi-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: multi-redis
          property: port
      - key: PGHOST
        fromService:
          type: postgres
          name: multi-postgres
          property: host
      - key: PGPORT
        fromService:
          type: postgres
          name: multi-postgres
          property: port
      - key: PGUSER
        fromService:
          type: postgres
          name: multi-postgres
          property: user
      - key: PGPASSWORD
        fromService:
          type: postgres
          name: multi-postgres
          property: password
      - key: PGDATABASE
        fromService:
          type: postgres
          name: multi-postgres
          property: database

  - type: worker
    name: multi-worker
    runtime: docker
    rootDir: worker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: multi-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: multi-redis
          property: port

databases:
  - name: multi-postgres
    databaseName: values
    user: postgres

  - name: multi-redis
    type: redis